### PR TITLE
Add Stremio guide links where possible

### PR DESCRIPTION
**Pull request by Viren070**
## Description

I added a link to [my guide](https://guides.viren070.me/stremio) where stremio is mentioned in other pages. 

I also made the links consistent by making sure they all are to the main page and using the same domain. I corrected/added query strings where necessary.

I removed [this guide](https://rentry.co/bye-sudo) because it has inaccuracies and lacks in information.

## Context 

Inaccuracies: 

> Keep in mind Real Debrid will only allow devices on the same network as you, 5 devices on the same network and 1 ip at a time.

Real debrid allows unlimited devices on 1 simultaneous IP. Not 5 devices. 

> Real Debrid is the cheapest 

Not true; alldebrid, debrid-link and torbox are cheaper ([Price Table](https://guides.viren070.me/stremio/setup#which-debrid-service-do-i-use))

As well as these inaccuracies, the guide is lacking in information and contains the bare minimum. I understand that my guide is filled with the maximum possible detail, making it long, but it is probably better to have an extensive guide.  

However, the inaccuracies can be fixed so it's not a problem as long as they are fixed. Therefore, this guide can also be kept, but I believe it would be better to have at least both guides linked.

Of course, this is up to you to decide, or you could make a suggestion on discord to discuss this change. 

## Types of changes
- [x] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:
- [x] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [x] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by itzCozi** [comment]
yea ok nerd

**Comment by itzCozi** [comment]
fixed inaccuracies

**Comment by Viren070** [comment]
> yea ok nerd

Not sure why you felt the need to throw insults around, but whatever. You seem to have fixed the innacuracies I pointed out 👍.

**Comment by itzCozi** [comment]
https://tenor.com/view/me-atrapaste-es-cine-its-cinema-cinema-esto-es-cine-gif-12869046600151364058

**Pull request merged**
