### PR TITLE
add exercism.org

### PR DESCRIPTION
**Pull request by suryaanshah**
## Description

add exercism.org in Programming Languages

## Context

It's a non-profit forever free great resource for developing fluency in many programming languages.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [x] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by InternetNinjo** [comment]
> ## Description
> 
> add exercism.org in Programming Languages
> ## Context
> 
> It's a non-profit forever free great resource for developing fluency in many programming languages.
> ## Types of changes
> 
>     * [ ]  Bad / Deleted sites removal
> 
>     * [ ]  Grammar / Markdown fixes
> 
>     * [x]  Content addition (sites, projects, tools, etc.)
> 
>     * [ ]  New Wiki section
> 
> 
> ## Checklist:
> 
>     * [x]  I have read the [contribution guide](https://fmhy.net/other/contributing).
> 
>     * [x]  I have made sure to [search](https://api.fmhy.net/single-page) before making any changes.
> 
>     * [x]  My code follows the code style of this project.

firefox_rTcQlVSi0r
it does seem free but what's this insider stuff lol?

**Comment by suryaanshah** [comment]
It's a non profit
But they have to make some money somehow
So they paywalled a few basic stuff like dark mode or Chatgpt help for problems etc 
But their main content remains and will remain always free of cost. That's their mission

**Comment by nbats** [comment]
thanks for sharing we'll test it soon

**Comment by nbats** [comment]
thanks for sharing but its already in the wiki under edu

**Comment by suryaanshah** [comment]
Weird that I couldn't find it. Alright, thank you!

**Pull request closed without merging**
