### PR TITLE
Add Clariss link

### PR DESCRIPTION
**Pull request by Sajeyks**
I added links to various tools found on [Clariss](https://www.clariss.xyz)

## Description

I added the links of various tools on the site called [Clariss](https://www.clariss.xyz):

1. Palette Generator:
   - Color palettes generator - https://www.clariss.xyz/generate-palettes-from-hex/
   - Generate color palettes from images - https://www.clariss.xyz/
   - Find color palettes - https://www.clariss.xyz/color-names/

2. Created a new section for color code converters
   - Hexacode ⇄ Pantone (pms) converter - https://www.clariss.xyz/converter/

I also corrected the grammar by updating the location of `or` in the list of tools wherever I added a link.

## Types of changes

- [ ] Bad / Deleted sites removal
- [X] Grammar / Markdown fixes 
- [X] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [X] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [X] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
Thank you we'll give the site a look soon

**Comment by Sajeyks** [comment]
Hello @nbats, 

I would like to humbly enquire why the PR failed to qualify or is the site underqualified to be added? Please let me know, it would mean a lot to me.

**Comment by nbats** [comment]
I'm sorry we just go through a lot of stuff so it sometimes takes a bit, but I did just get Clariss added in palette generators so it'll show up on the site soon.

**Comment by Sajeyks** [comment]
Okay Thank you for the update

**Pull request closed without merging**
