### PR TITLE
Update videopiracyguide.md

### PR DESCRIPTION
**Pull request by Aciduz**
Fixed name

## Types of changes

- [ ] Bad / Deleted sites removal
- [X ] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [X] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [X ] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [X ] My code follows the code style of this project.

### CODE REVIEW

**Comment by Aciduz** [comment]
Can you please recheck where you have put it on your list?

You have a website:

Hopcorn

 That's a fork of my site with only Movies and TV way above my site on the list.

I have Movies, TV, Live TV and anime.

https://movies.7xtream.com

**Comment by nbats** [comment]
Yeah sorry we're currently re-doing the entire section. Your site will most likely end up higher once we get to it, but it will take some time.

**Comment by nbats** [comment]
I'll bump it up a bit in the meantime

**Comment by Aciduz** [comment]
I thought so as there is alot of the sites that are currently not even online anymore..

But thank you 😊

**Comment by Aciduz** [comment]
Test mine on mobiles too has vibration feedbacks.. 👍

**Comment by Aciduz** [comment]
Hello, 

Just like to know one i couldn't understand the numbers for, the sorting 

**Site has some sorting options, but more content discoverability options would be nice.**


Maybe homepage? 


Because i have...

Collections 
Similar
Sort by network


See images 

Screenshot_20250107_100304_Edge
Screenshot_20250107_100702_Edge
Screenshot_20250107_100744_Edge

Rest i can improve or work on.

**Comment by Aciduz** [comment]
Thank you.. appreciate that.

**Comment by Aciduz** [comment]
I have added auto switch/skip:

"Has 19 servers, but does not auto-switch if ones fails. ⚠️"

Please can you check...

Screenshot_20250107_132641_Edge

**Comment by nbats** [comment]
Nice looks good, I'll get things readjusted soon.

**Comment by Aciduz** [comment]
Thanks

The score system added, becomes a challenge to me 🤣 I will be trying to add auto next episode tomorrow.

**Comment by nbats** [comment]
yeah it will I'm currently in the process of scoring them all, almost done.

**Comment by Aciduz** [comment]
So i figured i haved saved bookmarks meaning I have saving potential so I have added:

Series save episode data to auto play next episode  for ALL my embed players.

Marked it in the red box for clear reading.

Screenshot_2025-01-07_131427

**Comment by Aciduz** [comment]
You adding a place for API's???

https://embed.7xtream.com

**Comment by nbats** [comment]
yeah we have a streaming api list I can add it to, I'll do it soon

**Comment by Aciduz** [comment]
Have to show me where it is..

**Comment by nbats** [comment]
the list is under api tools

https://fmhy.net/devtools#api-tools

**Comment by nbats** [comment]
nice work looks good, I'll get your ui score adjusted soon

**Comment by Aciduz** [comment]
```09/01/2025

- Added all players sources with logos.
- Added player save, so it will start on the same player every time seperate for Movies & Series as players can be better either or.
- Added episode watching and history notifications.
- Added auto next episode
- Added Episode details.
- Improved styling for desktop and mobiles massively.
- Added Random watch button (HomePage).
- Added search by networks.
```

**Comment by nbats** [comment]
are you sure auto-next episode is working? doesn't seem to be for me

**Comment by Aciduz** [comment]
Let me look at it again today, I'm pulling a api from my embed and is a new thing so be of messing around with.

**Comment by Aciduz** [comment]
That still not quality?

**Comment by Aciduz** [comment]
Hello?

**Comment by nbats** [comment]
sorry but thats not really what we mean by auto-next, we mean allowing the next episode of a show to play without the user having the click anything

**Comment by Aciduz** [comment]
Okay I understand 👍

**Comment by Aciduz** [comment]
Not sure how your auto skip checking works but I have the same as this with a button to skip player, yet this apparently has auto skip? 
Screenshot_20250118_103801_Edge

**Comment by nbats** [comment]
Streamflix doesn't have auto-next as far as I know, they're working on it though.

**Comment by Aciduz** [comment]
Right bro spent the day improving my site gui and player 


So now it definitely 

Auto skips episodes 
Auto changes player if one is not working

You can go ahead and check now

Use first the player...

**Comment by nbats** [comment]
For auto-episode next it needs to actually start playing the video without user input. 

For auto-server switching its not working for me, it just says providers failed without checking anything but the first.

**Comment by Aciduz** [comment]
Yes bro open the video player check the Auto play next episode... Go to the end of a episode and it will automatically change the episode to the next one..

It's what I have been working on so I know it works i can even make you a video. 

The same player has 3 different sources, if one source is not available it skips it, just like videbinge just like sudo etc

**Comment by Aciduz** [comment]
But if your on about literally the player changing and it not starting to play on its own lol I can add the

?autoplay=true.

Because I think that's actually what you mean here.. as it changes just doesn't autoplay didn't think a user would actually like that

**Comment by Aciduz** [comment]
Yes okay i am adding it now to the player to autoplay when switching or when a user even hits the page it will play from last episode watched, as I have user data input saved and watch history etc.

**Comment by nbats** [comment]
sounds good just let me know when its been added

**Comment by Aciduz** [comment]
I am having to make an announcement in the server first if people want it to autoplay...

I have auto switch episode ready to play it just doesn’t "autoplay". 

This fix is as simple as adding ?autoplay=true to my embed 

But..

I know before I had complaints about adding autoplay so have to get back to you on this obviously for me the site is user experience more than anything else. 

The autoplay feature can be annoying for a user as they still want to be in control of certain things on a site. 

Like for now, I still have auto switch episode bro it's loads the next episode ready, it up just a user has to click play. So at least say I have it just doesn't "autoplay".

**Comment by nbats** [comment]
One option is to give users a toggle for autoplay so they can choose, but you guys scored well either way even if you decide not to add it.

**Comment by Aciduz** [comment]
Adding exactly what you said as I didn't even think of that idea.. 🤯


Try it now on site...

https://movies.7xtream.com/tv/125988


Hit the auto play auto skip toggle and put through series to the end of the episode to test it will auto skip and auto play now.

Screenshot_2025-01-22_112050

**Comment by nbats** [comment]
nice looks good, I'll get points updated in a bit

**Comment by Aciduz** [comment]
Added something pretty unique people won't offer 
Screenshot_20250124_114154_Chrome
Screenshot_20250124_114219_Chrome

**Comment by nbats** [comment]
nice thats awesome

**Comment by Aciduz** [comment]
Hey maybe should add points for mobile responsiveness, some of them at the top are awful!

**Comment by nbats** [comment]
yeah we're currently working on it, just gonna take a awhile to each tested.

**Comment by nbats** [comment]
@Aciduz hey just a heads up auto play / auto next seem to be broken

**Comment by Aciduz** [comment]
Just tested it and it's working... you mean on mobile?

**Comment by Aciduz** [comment]
@nbats ? i can get you a video if you want..

i see an issue with icons only atm

**Comment by Aciduz** [comment]
bro you actually gone and moved it without checking

**Comment by Aciduz** [comment]
https://github.com/user-attachments/assets/ca79bdea-578a-4d1d-b197-a2ade7651c36

**Comment by nbats** [comment]
idk what to tell ya, I'm trying in both chrome and firefox and it does not work for me at all. I've tried both player 1 and 2, and clicking the autoskip button under the episode. After one ends it just gives a blank screen, or loads the next episode but does not auto play.

**Comment by nbats** [comment]
image

**Comment by Aciduz** [comment]
on what series

**Comment by nbats** [comment]
this was squid games all seasons

**Comment by Aciduz** [comment]
i dont get it i have just test this on my side and works i can also video it you...

can you try opening in incognito

**Comment by nbats** [comment]
looks like its ublock origin blocking it from working

**Comment by Aciduz** [comment]
yes its not needed to have a ad blocker on my site 

if you tur ads off i also sandbox the players that can be sandboxed meaning no ads

**Comment by nbats** [comment]
I mean basically everyone uses ubo, and even when I turn ads off this is what it looks like 
image

**Comment by Aciduz** [comment]
turn ads off, manually refresh page if your in incognito as it will be needed

**Comment by nbats** [comment]
this is with them off and refreshed not in incognito 
image

**Comment by Aciduz** [comment]
https://github.com/user-attachments/assets/98556af4-032c-45c1-8eb7-29651410963e

**Comment by Aciduz** [comment]
check top right im incog

something on your system bro

i checked this method or 3 different browsers even with vpns on and off

**Comment by nbats** [comment]
I did, it works in chrome but not firefox

**Comment by Aciduz** [comment]
Google Chrome: 66.64%
Safari: 13.92%
Microsoft Edge: 4.55%
Mozilla Firefox: 2.18%
Opera: 3.02%
Samsung Internet: 3.04%
Others: 1.41%

**Comment by Aciduz** [comment]
i mean broooo....

**Comment by nbats** [comment]
I dont know what any of that means

**Comment by Aciduz** [comment]
its what percentage of people in the WORLD use what browser

**Comment by nbats** [comment]
alright fair enough, I'll mark your site as chromium required

**Comment by Aciduz** [comment]
yeah.. but that would mean you have to go through all sites testing all browsers no? lol

**Comment by nbats** [comment]
I do test with multiple browsers, the autonext used to work on firefox

**Comment by Aciduz** [comment]
i will download it now..

**Comment by Aciduz** [comment]
Autoplay Policy in Firefox
Issue: Firefox blocks autoplay for media elements with sound unless the user has explicitly allowed it.

I will try bypass it

**Comment by Aciduz** [comment]
autoplay works fine on firefox, its the ads not turning off.. i will fix it

**Comment by Aciduz** [comment]
added same ad blocker you have.. direct on site making no changes...

https://github.com/user-attachments/assets/739b70b8-31d7-4d1a-a2d0-db3fb2167218

**Comment by nbats** [comment]
I have the exact setup as you

**Comment by Aciduz** [comment]
maybe additional blocker install on your firefox?

**Comment by nbats** [comment]
alright fair enough I updated the note

**Comment by Aciduz** [comment]
Added Player 3, with absolutely no ads what so ever.. with 4K content. 

Screenshot_2025-01-29_114912

**Comment by nbats** [comment]
nice looks good I'll get things updated soon

**Comment by Aciduz** [comment]
Added something as a thank you.


Screenshot_2025-01-29_122503

**Comment by Aciduz** [comment]
Linked if clicked

**Comment by Aciduz** [comment]
hey bro added a filter for 4k movies



Screenshot 2025-01-31 160023



then choosing 7xteam (4k)

choose server and set to 4k server 



Screenshot 2025-01-31 160127

**Comment by nbats** [comment]
nice looks good, I'll get thing adjusted in the next update

**Comment by nbats** [comment]
I didn't even rate it I had help from others, I'll see if someone can try it again soon

**Comment by nbats** [comment]
alright two more people tested it and they both it was good so I'll get things updated soon

**Comment by Aciduz** [comment]
Really trying to squeeze my site to the bottom ain't you lol anything you rate the same above it 🤣👍 nice!

**Comment by BNX070** [comment]
> Really trying to squeeze my site to the bottom ain't you lol anything you rate the same above it 🤣👍 nice!

Your website is already starred, what more do you want? Pretty sure it isn't personal so why make it that

**Comment by nbats** [comment]
yep not personal, just many many many competitive sites now. Thats all

**Comment by nbats** [comment]
Yeah sorry I forgot about that, I'll adjust the scoring page now, and the order on the wiki will be adjusted later tonight/tomorrow when I send the updates for that too.

**Comment by Aciduz** [comment]
Hey bro was moving servers on my domain.. I made an announcement even in the discord but a removal of the link was issued on your site..

**Comment by nbats** [comment]
sorry I'll get it re-added soon

**Comment by Aciduz** [comment]
Okay, it was main:

movies.7xtream.com

And alternative 

cinema.7xtream.com

**Comment by Aciduz** [comment]
Hey bro can you do me a pre rating...

Want to see if i can get my site further up your page..

The new one will be when released:



https://movies2.7xtream.com

**Comment by nbats** [comment]
It looks good but I can't rate it right now, just let me know when its ready and I will

**Comment by Aciduz** [comment]
So it's ready, bro. I am going to keep it as an extra subdomain... whichever you rate the highest of my subdomains, use that link first..

**Comment by nbats** [comment]
alright I'll get it rated soon

**Comment by InternetNinjo** [comment]
> So it's ready, bro. I am going to keep it as an extra subdomain... whichever you rate the highest of my subdomains, use that link first..

you use vidsrc.cc and mark it as 7XSTREAM provider, you're not crediting the provider at all

**Comment by InternetNinjo** [comment]
> So it's ready, bro. I am going to keep it as an extra subdomain... whichever you rate the highest of my subdomains, use that link first..

you use [vidsrc.cc](http://vidsrc.cc/) and mark it as 7XSTREAM provider, you're not even naming it vidsrc

as for the 4k one, it's videasy.net
7xstream auto is from 111movies

**Comment by Aciduz** [comment]
Added our own custom player.

**Pull request merged**
