### PR TITLE
added "Letmefix Browser" extension to the Tab Manager list

### PR DESCRIPTION
**Pull request by git-kamesh**
## Description
Added "Letmefix browser" to the tab manager list

## Context
- Added "Letmefix browser" to the tab manager list
- Its a tab manager with many tab managin utilities
- Search and switch tabs
- Manage tab groups and pages

## Types of changes
- Content addition

## Checklist:
- [x] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [x] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by BNX070** [comment]
Doesn't seem safe but could be wrong, I'd suggest checking this before adding. Saying this because of the permissions it requires.

**Comment by 1Xnes** [comment]
seems sketchy i think

**Comment by nbats** [comment]
ty I added it to our link queue so we'll take a closer look at it when we can

**Comment by git-kamesh** [comment]
Hey, I'm the developer of this extension, please feel free to ask whatever the question you have.

I would like to add few more points,
- Its not a opensource extension (source code), since its a product having a premium version
- We don't track users or uniquely identify anyone, we collect four events "Installed", "uninstalled", "opened", "executed"
- We ask for more permissions becuase of the nature of this extension having the capabiulities for search tabs, search history and search bookmarks

**Comment by nbats** [comment]
thanks for all the info, I'll bump it up higher so it gets tested soon

**Pull request closed without merging**
